# Generated by Django 4.0 on 2022-07-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clinic',
            field=models.CharField(choices=[('GREITOJI ZIRAFA', 'Greitoji Zirafa'), ('2', 'Clinic2'), ('3', 'Clinic3'), ('4', 'Clinic4')], max_length=100),
        ),
    ]
