# Generated by Django 4.0 on 2022-07-02 07:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('is_owner', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(choices=[('C', 'Cat'), ('D', 'Dog'), ('R', 'Rabbit')], max_length=20)),
                ('breed', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('weight', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('birthday', models.DateField(blank=True, verbose_name='Birthday')),
                ('microchip', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=3)),
                ('microchip_code', models.CharField(blank=True, max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetapp.client')),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetapp.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, verbose_name='Visit date')),
                ('notes', models.CharField(max_length=300, verbose_name='Visit notes')),
                ('treatment', models.CharField(choices=[('M', 'Medical'), ('S', 'Surgical'), ('O', 'Other')], max_length=10)),
                ('anestesia', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vetapp.drug')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vetapp.petowner')),
                ('vet_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
        ),
    ]
