# Generated by Django 4.0 on 2022-07-09 06:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=10)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('clinic', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_owner', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(choices=[('CAT', 'Cat'), ('DOG', 'Dog'), ('RABBIT', 'Rabbit')], max_length=20)),
                ('breed', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6)),
                ('weight', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('birthday', models.DateField(blank=True)),
                ('microchip', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('microchip_code', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('notes', models.CharField(max_length=300)),
                ('treatment', models.CharField(choices=[('MEDICAL', 'Medical'), ('SURGICAL', 'Surgical'), ('OTHER', 'Other')], max_length=10)),
                ('drug', models.CharField(choices=[('ANTIPARASITICS', 'Antiparasitics'), ('ANTIFUNGALS', 'Antifungals'), ('STEROIDS', 'Steroids'), ('PAIN RELIEVERS', 'Pain Relievers')], max_length=100)),
                ('anestesia', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetapp.card')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetapp.pet')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
        ),
    ]
