# Generated by Django 4.0 on 2022-07-09 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('vetapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
