# Generated by Django 4.0 on 2022-07-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0002_alter_pet_microchip_alter_pet_sex_alter_pet_species_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='Client_details',
            new_name='client_details',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='Pet_details',
            new_name='pet_details',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='Visit_details',
            new_name='visit_details',
        ),
    ]
