# Generated by Django 4.0 on 2022-07-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0002_alter_card_clinic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='clinic',
            new_name='user_clinic',
        ),
    ]
