# Generated by Django 4.0 on 2022-07-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0003_rename_client_details_card_client_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_owner',
            field=models.CharField(max_length=3),
        ),
    ]
