# Generated by Django 4.0 on 2022-07-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0004_visit_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
