# Generated by Django 4.0 on 2022-07-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0004_alter_client_firstname_alter_client_is_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
    ]
