# Generated by Django 4.0 on 2022-07-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0005_alter_client_address_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
    ]
