# Generated by Django 4.0 on 2022-07-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0006_alter_client_address_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='microchip',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(max_length=20),
        ),
    ]
