# Generated by Django 4.0 on 2022-07-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0006_rename_age_pet_age_in_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='age_in_year',
            new_name='age_year',
        ),
    ]
