# Generated by Django 4.0 on 2022-07-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0007_alter_pet_birthday_alter_pet_microchip_alter_pet_sex_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='client_details',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='pet_details',
            new_name='pet',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='visit_details',
            new_name='visit',
        ),
    ]
