# Generated by Django 4.0 on 2022-07-09 10:30

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0008_pet_age_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age_year',
            field=computed_property.fields.ComputedTextField(blank=True, compute_from='get_age', editable=False, null=True),
        ),
    ]
