# Generated by Django 4.0 on 2022-07-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0009_alter_pet_age_month_alter_pet_age_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age_month',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='age_year',
        ),
    ]
