# Generated by Django 4.0 on 2022-07-09 10:51

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0010_remove_pet_age_month_remove_pet_age_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='pet_age_year',
            field=computed_property.fields.ComputedTextField(compute_from='get_age', editable=False, null=True),
        ),
    ]
